name: Auto Build

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set Timezone
              run: |
                sudo -E timedatectl set-timezone Asia/Shanghai

            - name: Set Tag
              id: tag
              run: |
                tag=$(date +"v%Y.%m.%d.%H%M%S")
                echo "tag=$tag" >> $GITHUB_OUTPUT

            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: 'stable'
                check-latest: true

            - name: Build
              run: |
                GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.darwin.amd64 ./
                GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.darwin.arm64 ./
                GOOS=linux GOARCH=386 go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.linux.386 ./
                GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.linux.amd64 ./
                GOOS=windows GOARCH=386 go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.windows.386.exe ./
                GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.windows.amd64.exe ./

            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                files: bin/*
                tag_name: ${{ steps.tag.outputs.tag }}
                draft: false
                prerelease: false