name: Auto Build

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install Golang
              run: |
                sudo -E apt update
                sudo -E apt install golang -y

            - name: Set Timezone
              run: |
                sudo -E timedatectl set-timezone Asia/Shanghai

            - name: Set Tag
              id: tag
              run: |
                tag=$(date +"v%Y.%m.%d.%H%M%S")
                echo "tag=$tag" >> $GITHUB_OUTPUT

            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Build
              run: |
                go mod init checkSSLProtocol
                go mod tidy
                mkdir bin
                go env -w GOOS=linux
                go env -w GOARCH=amd64
                go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.linux.amd64 ./
                go env -w GOOS=windows
                go env -w GOARCH=amd64
                go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.windows.amd64.exe ./
                go env -w GOOS=linux
                go env -w GOARCH=386
                go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.linux.386 ./
                go env -w GOOS=windows
                go env -w GOARCH=386
                go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }}" -o ./bin/checkSSLProtocol.windows.386.exe ./
            
            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                files: bin/*
                tag_name: ${{ steps.tag.outputs.tag }}
                draft: false
                prerelease: false
