name: Auto Build

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install Golang
              run: |
                sudo -E apt update
                sudo -E apt install golang -y

            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set Tag
              id: tag
              run: |
                tag=$(date +"v%Y.%m.%d")
                echo "tag=$tag" >> $GITHUB_OUTPUT

            - name: Set Timezone
              run: |
                sudo -E timedatectl set-timezone Asia/Shanghai

            - name: Build
              run: |
                go mod init $GITHUB_REPOSITORY
                go mod tidy
                sudo -E mkdir bin
                cd bin
                datetime=$(date "+%Y-%m-%d %H:%M:%S")
                go build -ldflags "-X main.version=${{ steps.tag.outputs.tag }} -X main.buildTime=$datetime" ../
            
            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                files: bin/*
                tag_name: ${{ steps.tag.outputs.tag }}
                draft: false
                prerelease: false
