name: Auto Build

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: 'stable'
                check-latest: true
                architecture: 'x64'

            - name: Build
              run: |
                go build -v -o ./bin/ ./

            - name: Set Tag
              id: tag
              run: |
                tag=$(date +"v%Y.%m.%d.%H%M%S")
                echo "tag=$tag" >> $GITHUB_OUTPUT

            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                files: bin/*
                tag_name: ${{ steps.tag.outputs.tag }}
                draft: false
                prerelease: false